# Generated by Django 4.2.27 on 2025-12-31 12:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.CharField(max_length=10)),
                ('score', models.IntegerField(default=0)),
                ('is_host', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=True)),
                ('hand', models.JSONField(default=list)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_code', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting for players'), ('PLAYING', 'Game in progress'), ('GAME_OVER', 'Game finished')], default='WAITING', max_length=10)),
                ('max_rounds', models.IntegerField(default=10)),
                ('current_round', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('czar_id', models.UUIDField(blank=True, null=True)),
                ('current_question', models.TextField(blank=True, null=True)),
                ('phase', models.CharField(choices=[('WAITING', 'Waiting'), ('SUBMISSION', 'Card Submission'), ('PICKING', 'Czar Picking'), ('TRANSITIONING', 'Round Transition'), ('GAME_OVER', 'Game Over')], default='WAITING', max_length=15)),
                ('round_expires_at', models.DateTimeField(blank=True, null=True)),
                ('black_deck', models.JSONField(default=list)),
                ('white_deck', models.JSONField(default=list)),
                ('last_round_winner_id', models.UUIDField(blank=True, null=True)),
                ('last_round_winner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_round_winning_card', models.TextField(blank=True, null=True)),
                ('last_round_number', models.IntegerField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to='core.anonymoususer')),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pack')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.IntegerField()),
                ('card_text', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.room')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.room'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.anonymoususer'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('card_type', models.CharField(choices=[('black', 'Black (Question)'), ('white', 'White (Answer)')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.pack')),
            ],
        ),
        migrations.AddIndex(
            model_name='anonymoususer',
            index=models.Index(fields=['session_key'], name='core_anonym_session_648748_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('room', 'player', 'round_number')},
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['room', 'is_online'], name='core_player_room_id_adcda4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('user', 'room')},
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['pack', 'card_type'], name='core_card_pack_id_f9aee8_idx'),
        ),
    ]
