# Generated by Django 4.2.27 on 2025-12-31 13:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCallSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signal_type', models.CharField(choices=[('offer', 'WebRTC Offer'), ('answer', 'WebRTC Answer'), ('ice_candidate', 'ICE Candidate'), ('renegotiate', 'Renegotiation Request')], max_length=20)),
                ('signal_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('from_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_signals', to='core.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_signals', to='core.room')),
                ('to_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_signals', to='core.player')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['to_player', 'delivered'], name='core_videoc_to_play_87e7ce_idx'), models.Index(fields=['room', 'created_at'], name='core_videoc_room_id_4b245d_idx')],
            },
        ),
        migrations.CreateModel(
            name='VideoCallParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_enabled', models.BooleanField(default=True)),
                ('audio_enabled', models.BooleanField(default=True)),
                ('screen_sharing', models.BooleanField(default=False)),
                ('is_connected', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_calls', to='core.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_participants', to='core.room')),
            ],
            options={
                'indexes': [models.Index(fields=['room', 'is_connected'], name='core_videoc_room_id_86e200_idx')],
                'unique_together': {('room', 'player')},
            },
        ),
    ]
